// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRaf9oTJmjIRBtxscoCokMr-rvgWYDjFY',
    appId: '1:404396896334:web:27783f25fb7a753221931f',
    messagingSenderId: '404396896334',
    projectId: 'kasir-euy',
    authDomain: 'kasir-euy.firebaseapp.com',
    databaseURL: 'https://kasir-euy-default-rtdb.firebaseio.com',
    storageBucket: 'kasir-euy.appspot.com',
    measurementId: 'G-2P5WMPYGE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNaUQ6REJ99KgczPNLG462G5-pvMofIhw',
    appId: '1:404396896334:android:b07d507815000eea21931f',
    messagingSenderId: '404396896334',
    projectId: 'kasir-euy',
    databaseURL: 'https://kasir-euy-default-rtdb.firebaseio.com',
    storageBucket: 'kasir-euy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv-c9-emcJkZDi-ILzMSGPIoxN0ZFrGD4',
    appId: '1:404396896334:ios:34a041fe6404490d21931f',
    messagingSenderId: '404396896334',
    projectId: 'kasir-euy',
    databaseURL: 'https://kasir-euy-default-rtdb.firebaseio.com',
    storageBucket: 'kasir-euy.appspot.com',

    iosClientId: '404396896334-eqbdinu02k6f515u62tsnomtdfmllmhq.apps.googleusercontent.com',

    iosBundleId: 'com.example.kasirEuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv-c9-emcJkZDi-ILzMSGPIoxN0ZFrGD4',
    appId: '1:404396896334:ios:34a041fe6404490d21931f',
    messagingSenderId: '404396896334',
    projectId: 'kasir-euy',
    databaseURL: 'https://kasir-euy-default-rtdb.firebaseio.com',
    storageBucket: 'kasir-euy.appspot.com',

    iosClientId: '404396896334-eqbdinu02k6f515u62tsnomtdfmllmhq.apps.googleusercontent.com',

    iosBundleId: 'com.example.kasirEuy',
  );
}
